# this exists only so that the process of pulling from docker hub occurs
# at build time rather than at runtime
# i.e. CDK will pull this down and push it into a region specific CDK asset
FROM rclone/rclone:1.62.2
